### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by panwubin470** [SalikLP/classification-of-encrypted-traffic#1]
Hello Salik,

Recently, I am interested in encrypted traffic classificaton, could I learn about your master thesis based on Deep learning? Thanks!

Wubin Pan
wbpan@njnet.edu.cn

**Comment by Arhjorth** [comment]
Hey Wubin

Thank you for your interest. We are still in an early stage of the project and therefore do not have much to share with you. 
Our project will be handed in on the 17. of June 2018.
We will include the project report on github. 

Best regards 
Andreas
