### ISSUE TITLE
about the origin traffic 

### ISSUE THREAD

**Issue by Akrusher** [SalikLP/classification-of-encrypted-traffic#2]
I am very interested in the work of your encrypted traffic classification.
But I see that only the extracted data about the header is in your dataset directory。
I am looking for the original pcap traffic file，thank you very much.

**Comment by SalikLP** [comment]
Hi

Unfortunately we don't have access to the original pcap files as they were handed over to Napatech. I would however think that it should be possible to generate some quite easily.
