### ISSUE TITLE
Detail about data preprocessing

### ISSUE THREAD

**Issue by wawales** [SalikLP/classification-of-encrypted-traffic#3]
Do u remove the ip/port in data preprocessing?
I think some of the aplications have unique port in headers, it can be classified by some head paser easily.

**Comment by SalikLP** [comment]
Hi 
Yes as stated in the report we remove both port, IP 
and Mac address as that would have made the classification trivial.

**Comment by wawales** [comment]
Okay, I got that. Thanks for your reply.




| |
wawa
|
|
邮箱：woshixwmr1@163.com
|

Signature is customized by Netease Mail Master

On 01/13/2020 15:26, Salik Lennert Pedersen wrote:

Hi
Yes as stated in the report we remove both port, IP
and Mac address as that would have made the classification trivial.
